sonata_media:
    # if you don't use default namespace configuration
    # class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
                
        news:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image

            formats:
                small: { width: 150 , quality: 95}
                big:   { width: 500 , quality: 90}
                wide:   { width: 600 , quality: 90}
                square: { width: 100, height: 100 , quality: 80}
                
        recette:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image

            formats:
                small: { width: 150 , quality: 95}
                big:   { width: 600 , quality: 95}
                square: { width: 270, height: 270, quality: 90}
                squareFav: { width: 100, height: 100, quality: 90}
                
        ingredient:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image

            formats:
                small: { width: 150 , quality: 95}
                big:   { width: 480 , quality: 95}
                square: { width: 100, height: 100, quality: 90}
                
        badge:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 48, height: 48 , quality: 95}
                square: { width: 100, height: 100, quality: 90}
                
        avatar:
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 48, height: 48 , quality: 95}
                square: { width: 270, height: 270, quality: 90}
                
                
        

    cdn:
        server:
            path: http://localhost/MealSquare/web/uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
            
    providers:
        image:
            resizer: sonata.media.resizer.square
            allowed_extensions: ['jpg', 'png', 'gif', 'jpeg']
            allowed_mime_types: ['image/pjpeg','image/jpeg','image/png','image/x-png', 'image/gif']
