sonata_news:
    title:        Sonata Project
    link:         http://sonata-project.org
    description:  Cool bundles on top of Symfony2
    salt:         'secureToken'
    permalink_generator: sonata.news.permalink.date # sonata.news.permalink.category

    comment:
        notification:
            emails:   [email@example.org, email2@example.org]
            from:     no-reply@sonata-project.org
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'
          
    class:
        post:       Application\Sonata\NewsBundle\Entity\Post
        comment:    Application\Sonata\NewsBundle\Entity\Comment
        media:      Application\Sonata\MediaBundle\Entity\Media
        user:       Application\Sonata\UserBundle\Entity\User
        
    admin:
        post:
            class:       Sonata\NewsBundle\Admin\PostAdmin
            controller:  SonataAdminBundle:CRUD
            translation: SonataNewsBundle
        comment:
            class:       Sonata\NewsBundle\Admin\CommentAdmin
            controller:  SonataAdminBundle:CRUD
            translation: SonataNewsBundle

            

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataNewsBundle: ~
                    SonataNewsBundle: ~
